## numpy array and basics
learning about numpy with chaiaurcode 💻

In [1]:
import numpy as np


### creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: \n", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: \n", arr_2d)

1D array: 
 [1 2 3 4 5]
2D array: 
 [[1 2 3]
 [4 5 6]]


### list v/s numpy array


In [3]:
py_list = [1,2,3]
print("Python list multiplication: ", py_list * 2)


np_array = np.array([1, 2, 3]) # element wise multiplication
print("Python array multiplication: ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(10_000_000)]
print("\nList operation time: ", time.time() - start)


start = time.time()
np_array = np.arange(10_000_000) * 2
print("\nNumpy operation time: ", time.time() - start)


Python list multiplication:  [1, 2, 3, 1, 2, 3]
Python array multiplication:  [2 4 6]

List operation time:  0.8913118839263916

Numpy operation time:  0.0417172908782959


### creating array from scratch

In [4]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((4, 2))
print("ones array: \n", ones)

full = np.full((4, 4), 77)
print("full array: \n", full)

random = np.random.random((2,3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequence array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
full array: 
 [[77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]
 [77 77 77 77]]
random array: 
 [[0.77608566 0.10657884 0.98060621]
 [0.77551599 0.97182953 0.21188961]]
sequence array: 
 [ 0  2  4  6  8 10]


### vector, matrix and tensor

In [6]:
vector = np.array([1, 2, 3])
print("vector: ", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix: \n", matrix)


tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print("tensor: \n", tensor)

vector:  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])

print("shape: ", arr.shape)
print("dimension: ", arr.ndim)
print("size: ", arr.size)
print("data type: ", arr.dtype)

shape:  (2, 3)
dimension:  2
size:  6
data type:  <U21


### array reshaping

In [21]:
arr = np.arange(12)
print("original array: ", arr)

reshaped_arr = arr.reshape((4, 3))
print("\nreshaped array: \n", reshaped_arr)

flattened = reshaped_arr.flatten()
print("\nflattened array: ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped_arr.ravel()
print("\nraveled array: ", raveled)

# transpose
transpose = reshaped_arr.T
print("\ntransposed array: \n", transpose)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

transposed array: 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
