## numpy array operations 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("array: ", arr)

print("basic slicing: ", arr[2:7])

print("with step slicing: ", arr[1:8:2])

print("negative indexing: ", arr[-3])




array:  [ 1  2  3  4  5  6  7  8  9 10]
basic slicing:  [3 4 5 6 7]
with step slicing:  [2 4 6 8]
negative indexing:  8


---

### on 2D arrays

In [3]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("original 2D array: \n", arr_2d)

print("specific element: ", arr_2d[1, 2]) # --> 1st row & 2nd element (goes like, 0th row, 1st row, 2nd row & same for column)

print("entire row: ", arr_2d[2])

print("entire column: ", arr_2d[:, 1])


original 2D array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
specific element:  6
entire row:  [7 8 9]
entire column:  [2 5 8]


---

### sorting

In [4]:
unsorted = np.array([3, 1, 4, 5, 2, 9, 2, 6])
print("unsorted array: ", unsorted)

print("sorted array: ", np.sort(unsorted))


arr_2d_unsorted = np.array([[3,1], [1,2], [2,3]])
print("unsorted 2D array: \n", arr_2d_unsorted)

print("sorted 2d array by col: \n", np.sort(arr_2d_unsorted, axis=0)) # axis = 0
print("sorted 2d array by col: \n", np.sort(arr_2d_unsorted, axis=1)) # axis = 1


unsorted array:  [3 1 4 5 2 9 2 6]
sorted array:  [1 2 2 3 4 5 6 9]
unsorted 2D array: 
 [[3 1]
 [1 2]
 [2 3]]
sorted 2d array by col: 
 [[1 1]
 [2 2]
 [3 3]]
sorted 2d array by col: 
 [[1 3]
 [1 2]
 [2 3]]


---

### filtering

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_nums = numbers[numbers % 2 == 0]
print("even numbers: ", even_nums)

even numbers:  [ 2  4  6  8 10]


### filter with mask

In [6]:
mask = numbers > 5
print("numbers greater than 5: ", numbers[mask])

numbers greater than 5:  [ 6  7  8  9 10]


---

### fancy indexing v/s np.where()

In [ ]:
indices = [0, 2, 4]

print(numbers[indices])



where_result = np.where(numbers > 5)

print(where_result)
print("np where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
np where:  [ 6  7  8  9 10]


---
### creating array from conditions

In [12]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [ ]:
"""

if(numbers > 5):
    numbers * 4
else:
    numbers

"""

---
### adding and removing data

In [16]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

summing_arr = arr1 + arr2
print(summing_arr)

combined = np.concatenate((arr1, arr2))
print("combined array: ", combined)

[5 7 9]
combined array:  [1 2 3 4 5 6]


### array compatibility

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6,10])
c = np.array([7,8,9])

print("compatibility shapes:", a.shape == b.shape)

compatibility shapes: False


In [ ]:
original = np.array([[1,2], [3,4]])
new_row = np.array([5,6])

# vstack() is used to add rows
with_new_row = np.vstack((original, new_row))
print("original: \n", original)
print("with new row: \n", with_new_row)

# hstack() is used to add cols
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("with new col: \n", with_new_col)

original: 
 [[1 2]
 [3 4]]
with new row: 
 [[1 2]
 [3 4]
 [5 6]]
with new col: 
 [[1 2 7]
 [3 4 8]]


---
### deletion

In [29]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr, 2)

print("array after deletion: ", deleted)

array after deletion:  [1 2 4 5]
